### PR TITLE
OADP-2074 Make PVC clone storageclass, accessmodes, resources consistent with sourcePVC

### LINKED ISSUE #235: OADP-2074 Mirrored PVC `snapcontent-*-pvc` can have inconsistent storageclass from sourcePVC using values from unrelated configmap options for volsync operations
See 
https://issues.redhat.com/browse/OADP-1821?focusedId=22408832&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22408832

This PVC sometimes have incorrect StorageClassName that did not match values set in DPA.
https://github.com/migtools/volume-snapshot-mover/blob/f3057bdb11eca80649a5a1a88229ed717c03a20d/controllers/pvc.go#L62-L75

### PR DESCRIPTION
**Pull request by kaovilai**
Make it so volumeOptionsForStorageClasses is for volsync operations only.

[OADP-2074](https://issues.redhat.com/browse/OADP-2074)

Closes #235

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

### CODE REVIEW

**Comment by eemcmullan** [comment]
@kaovilai this is the way we used to created the cloned PVC, and it does not work for the new CephFS feature

**Comment by eemcmullan** [comment]
@kaovilai No - need to figure out why this happens. I tested yesterday with 10 backups and reproduced twice. It's odd

**Comment by kaovilai** [comment]
My hunch is that the getConfigMap function used is returning nil (either error or configmap not found)when it shouldn't.

**Comment by shubham-pampattiwar** [comment]
Closing this PR in favor of https://github.com/migtools/volume-snapshot-mover/pull/237

**Comment by shubham-pampattiwar** [comment]
Closing this PR in favor of https://github.com/migtools/volume-snapshot-mover/pull/237

**Pull request closed without merging**
