### PR TITLE
Add batching status to VSB/VSR printer columns

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Related OADP Operator PR: https://github.com/openshift/oadp-operator/pull/999

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]
/cherry-pick oadp-1.2
/unassign @kaovilai

**Comment by kaovilai** [comment]
well that did not unassign anything.
/unassign @kaovilai

**Review by weshayutin — APPROVED** [review]

**Pull request merged**
