### PR TITLE
Improve perf next level

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Controller image: `quay.io/spampatt/volume-snapshot-mover:perf-bell-labs`

### CODE REVIEW

**Review by eemcmullan — APPROVED** [review]

**Comment by kaovilai** [comment]
Wow. next level.

**Comment by weshayutin** [comment]
oh lordy lordy.. nice tiger! /me looking

**Comment by kaovilai** [comment]
> @kaovilai: only [migtools](https://github.com/orgs/migtools/people) org members may request cherry-picks. You can still do the cherry-pick manually.

sad...

**Pull request closed without merging**
