### PR TITLE
OADP-1941: Remove securityContext default to true

### PR DESCRIPTION
**Pull request by eemcmullan**

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by weshayutin** [comment]
data and file permissions are correct :) well done!

```
sh-4.4$ cd /var/lib/mysql/
sh-4.4$ ls -la
total 24
drwxrwsr-x. 4 root  mysql  4096 Jun  2 18:08 .
drwxr-xr-x. 1 root  root     53 Jun 20  2022 ..
drwxrws---. 6 mysql mysql  4096 Jun  2 18:08 data
drwxrws---. 2 root  mysql 16384 Jun  2 17:48 lost+found
srwxrwxrwx. 1 mysql mysql     0 Jun  2 18:08 mysql.sock
sh-4.4$ cat /etc/passwd | grep mysql
mysql:x:27:27:MySQL Server:/var/lib/mysql:/sbin/nologin
sh-4.4$ cat /etc/group | grep mysql
root:x:0:mysql
mysql:x:27:
sh-4.4$ 
```

**Pull request merged**
